### ISSUE TITLE
some glowstone blocks added by Infernal Expansion have missing textures.

### ISSUE THREAD

**Issue by Wedge1453** [Eltrut-Co/Lepton#29]
![2021-08-19_11 34 57](https://user-images.githubusercontent.com/76813383/130054573-2c2c4dd8-ceaa-4e6c-83e8-f9500bf681de.png)

**Comment by EltrutLikes** [comment]
This is fixed indev, I just forgot to release another version so thanks for that reminder!

**Comment by EltrutLikes** [comment]
The new version fixing this has just been released, feel free to reopen if I overlooked something.

**Comment by Wedge1453** [comment]
a stair and 2 walls still have render issues:
![2021-08-30_01 36 25](https://user-images.githubusercontent.com/76813383/131980671-f6698f2e-a2a7-4e7d-80f0-6601e5da6c86.png)
